### ISSUE TITLE
Carriage return stays inside Vim

### ISSUE THREAD

**Issue by daniellandau** [ardagnir/athame#11]
It seems that most of the time when I hit enter, I just move to the next line in the Vim buffer. Some times it seems to be passed on and the command gets executed but most of the time not. 

In normal mode, it seems to work better if I wait a couple of seconds after the previous key stroke before hitting enter. In insert mode, it sometimes works when cursor is not at the end of the line but not always.

All the times I managed to get the carriage return through where in python, not even once in bash. (I launched both from zsh which doesn't use readline)

**Comment by ardagnir** [comment]
Thanks, this should be fixed now.

**Comment by daniellandau** [comment]
Works, so cool, thanks!
