### ISSUE TITLE
Neovim?

### ISSUE THREAD

**Issue by sethwoodworth** [ardagnir/athame#12]
I see that you have contributed to neovim.  Have you considered using Neovim for this purpose rather than stock vim?

**Comment by braham-snyder** [comment]
relevant neovim issue: neovim/neovim#1750

as of now, https://github.com/mhinz/neovim-remote is a "temporary solution"

**Comment by ardagnir** [comment]
Thanks for the link! I tried neovim-remote a while back but it was a) more of a way to make neovim more like --remote than a full backwards compatible impl that would be needed here and b) very buggy. These might no longer be the case, so if anybody can get Athame to work with neovim-remote, let me know and I'll add instructions to the readme.

I have a plan for adding support for the new vim jobs in athame 0.9 or 0.10 and if neovim jobs are similar enough (I think they are), I'll add native neovim support too while I'm at it. This will hopefully be by the end of the year.

**Comment by snoblenet** [comment]
Has there been any progress on this issue? Cheers.

**Comment by ardagnir** [comment]
The unstable 1.0 branch of athame supports the new v8 style async that is
very similar to neovim. If there aren't any major hurdles, I'll probably
add neovim support in athame 1.1 (hopefully within the next month or two,
but it depends how much free time I have)

**Comment by snoblenet** [comment]
I don't normally read C at all, but I'm thinking that to support Neovim, you just need a switch in `athame/athame_util.h` that changes `vim` to `nvr` and a prompt to check that the Neovim user has installed Neovim-Remote.

**Comment by ardagnir** [comment]
Athame already supports different binaries using the vimbin flag in the
setup script. The problem is that Neovim-Remote, last I checked, is both
very buggy, and behaves differently than normal vim's remote. It'll be
easier to just use Neovim jobs than Neovim-Remote, but there's nothing
stopping you from trying.

**Comment by vyzyv** [comment]
Any progress regarding neovim support?

**Comment by ardagnir** [comment]
There's basic neovim support in the neovim branch. It will get rolled out to master in the 1.1 release.
