### ISSUE TITLE
Cannot get to run in Ubuntu 14.10 using zsh for install

### ISSUE THREAD

**Issue by rhgraysonii** [ardagnir/athame#13]
I have followed the README directly and am unable to get things up and running. I'm really excited to try it out but have hit a wall attempting to figure out how to get it to start. I have tried checking /bin and /usr/bin but get nothing related in there, and wasn't sure where to go next.

**Comment by rhgraysonii** [comment]
Feel free to close if I'm just silly and did something wrong.

**Comment by frioux** [comment]
I'm interested in this too, but I don't think zsh uses readline, because zsh has it's own key-bind support etc.  I could be wrong of course.

**Comment by rhgraysonii** [comment]
Ah I see that would make sense. It is quite late here so I'm not inclined to try now, but I will experiment with it and report back tomorrow @frioux . I really appreciate the response. Seriously, good eye. Never would have caught that myself.

**Comment by aaronmcadam** [comment]
I don't think zsh is supported. From https://github.com/ardagnir/athame/issues/9:

> zsh uses zle rather than readline so I wouldn't expect athame to work like it does in bash

**Comment by rhgraysonii** [comment]
Thanks!

**Comment by ardagnir** [comment]
Athame supports zsh now
