### ISSUE TITLE
Zsh support

### ISSUE THREAD

**Issue by ardagnir** [ardagnir/athame#14]
After looking at the Zle code, it should be relatively easy to add zsh support:
- Step 1: Pass readline-specific functions/variables to athame (like rl_redisplay) instead of hardcoding readline specific ones. (Relatively easy)
- Step 2: Add the three athame function calls to zle/zle_main.c and add athame.c/h to zle. (Even easier)
- Step 3: Everything should just work at this point. But it won't. Fix whatever doesn't work. (The hard part)

**Comment by ardagnir** [comment]
Early Zsh support is now in the unstable 0.3 branch. It's still buggy and Zsh history integration is not done yet.

Side note: Don't read Zle's src code unless you enjoy bleeding from your eyeballs.

**Comment by NSinopoli** [comment]
:+1:

**Comment by ardagnir** [comment]
Zsh support is in master. There's unicode problems and right-prompt is not supported but I''ll make seperate issues for those.

**Comment by NSinopoli** [comment]
Great work! Can't wait to try this out.
