### ISSUE TITLE
Zsh right prompt support

### ISSUE THREAD

**Issue by ardagnir** [ardagnir/athame#17]
Zsh's right prompt is not supported.

**Comment by Froziph** [comment]
Whats the status on this? Is it "impossible", so other options maybe should be explored (by myself, in my case adding the time to the left prompt instead of having it at the right)

**Comment by ardagnir** [comment]
It's not impossible. It'll get fixed eventually. But I think showing the mode is what breaks the right prompt. If you use ATHAME_SHOW_MODE=0, it should work (or it does for me).

**Comment by Froziph** [comment]
I tried using ATHAME_SHOW_MODE=0. The right prompt is there, as long as the line is active. When i execute the line the right prompt disappears

**Comment by ardagnir** [comment]
That is fixed now. The right prompt is still broken when ATHAME_SHOW_MODE=1 though.

**Comment by ardagnir** [comment]
Fixed, even when ATHAME_SHOW_MODE=1
