### ISSUE TITLE
Zsh plugins

### ISSUE THREAD

**Issue by Froziph** [ardagnir/athame#20]
I use a couple of zsh plugins (with oh-my-zsh), most importantly the "sudo" plugin making a double tab on escape produce a sudo in front of the current line, or previous line if current line is empty.

These do not work with athame installed, i tried 
"function zle-line-init(){
  echoti rmkx
}
zle -N zle-line-init"

in my .zshrc, but it didn't fix the problem. 

Any ideas?

**Comment by Froziph** [comment]
Oh.. Escape is obviously 'taken' by this now, just tried ZSH's default vi mode which also makes the plugin unuseable. While i'd love to be able to keep this plugin, the problem isn't here. I apologize for the false report.

**Comment by ardagnir** [comment]
As you figured out, vim grabs almost all the keys, so keymaps have to be done in vimscript. You can, for example, add "nnoremap <ESC> Isudo " to your athamerc. Then if you hit <ESC> twice from insert mode, it will add sudo in front of your command.
