### ISSUE TITLE
ZSH "list options"

### ISSUE THREAD

**Issue by Froziph** [ardagnir/athame#22]
When i tab through suggestions, it is bugging. It only highlights the current suggestion, and all the other suggestions are hidden. When moving on to the next, it lights up, and the old selection is listed for a short moment and then disappears aswell. They are still in the positions they would be in if they were visible, they are just hidden.

Each new line (after an enter) also shortly blinks after a moment.

I have ATHAME_SHOW_MODE=0, if that makes a difference.

I hope these constant issue posts are a help and not an annoyance.

**Comment by ardagnir** [comment]
These are very helpful. Feel free to post any issues you find.

What do you mean each new line blinks? Is this during tab completion or in general?

**Comment by Froziph** [comment]
Whenever a new line comes (from executing the previous one), after a very short moment, the line clears (disappears), and reappears. This is what i call "blinking". Let me know if you need further explanation of the issue.

**Comment by ardagnir** [comment]
List options should be fixed. I haven't been able to reproduce the blinking. Does it still happen in the most recent version?
