### ISSUE TITLE
Option to change installation prefix

### ISSUE THREAD

**Issue by memeplex** [ardagnir/athame#26]
It would be nice of the installation script to allow to install the patched readline using another prefix as ~/.local.

**Comment by kovetskiy** [comment]
+1
it's really necessary

**Comment by ardagnir** [comment]
The setup script lets you pick the directories now. This is mostly for compatibility, but I'll double check that local works before closing this.

**Comment by ardagnir** [comment]
You can now change the installation prefix by using --prefix=$HOME/.local/ or whatever in the setup script. You can also add --nosudo to bypass running sudo if you build locally.
