### ISSUE TITLE
Issues with multi line editing in IPython

### ISSUE THREAD

**Issue by infokiller** [ardagnir/athame#30]
After pressing the return key in a multi line statement, instead of continuing the editing on the next line, the insert mode indication at the bottom disappears and then when I start typing again the cursor position is set to the beginning of the line.
For example, after typing the following and pressing return:

```
for i in range(3):
```

I would expect the cursor position to be indented and to stay in insert mode.

I'm using IPython 4.0.1.

**Comment by ardagnir** [comment]
This is fixed. I'm keeping this bug open because there are other issues with multiline editing, ie that athame effectively breaks history into single lines.

**Comment by ardagnir** [comment]
The original bug is fixed. I'm closing this and opening a new bug for full multiline editing support
