### ISSUE TITLE
OS X: ./readline_athame_setup.sh fails Athame Vim Integration Test 2

### ISSUE THREAD

**Issue by braham-snyder** [ardagnir/athame#38]
I'm running OS X 10.11 (El Capitan). This is the end of ./readline_athame_setup.sh's output:

```
installing vi.gmo as /Users/bs/athame/test/build/usr/local/share/locale/vi/LC_MESSAGES/ba
sh.mo
installing zh_CN.gmo as /Users/bs/athame/test/build/usr/local/share/locale/zh_CN/LC_MESSA
GES/bash.mo
installing zh_TW.gmo as /Users/bs/athame/test/build/usr/local/share/locale/zh_TW/LC_MESSA
GES/bash.mo
if test "bash" = "gettext-tools"; then \
          /bin/sh /Users/bs/athame/bash-4.3_tmp/./support/mkinstalldirs /Users/bs/athame/
test/build/usr/local/share/gettext/po; \
          for file in Makefile.in.in remove-potcdate.sin quot.sed boldquot.sed en@quot.he
ader en@boldquot.header insert-header.sin Rules-quot   Makevars.template; do \
            /usr/local/bin/ginstall -c -m 644 ./$file \
                            /Users/bs/athame/test/build/usr/local/share/gettext/po/$file;
 \
          done; \
          for file in Makevars; do \
            rm -f /Users/bs/athame/test/build/usr/local/share/gettext/po/$file; \
          done; \
        else \
          : ; \
        fi
Testing Athame Shell...
Test 1:
Success!

Test 2:
Failed at high speed. Retrying at slower speed
Success!

Test 3:
Failed at high speed. Retrying at slower speed
Success!

Test 4:
Success!

Testing Athame Vim Integration...
Test 1:
Success!

Test 2:
Failed at high speed. Retrying at slower speed
Failed at slow speed.

Test Failed
Failed tests: 2

What now?
v: view failures
C: *DANGEROUS* continue anyway
x: exit
v
Script started on Thu Oct  6 01:23:06 2016
command: bash -c ../charread.sh .15 input_text | /Users/bs/athame/test/build/bin/bash -i
bash-4.3$ unset HISTFILE
bash-4.3$
bash-4.3$
bash-4.3$ iecho "test 2kj2h~b~A" > out2
bash: iecho: command not found
bash-4.3$ exit

Script done on Thu Oct  6 01:23:19 2016
1d0
< TesT 2
```

I've prayed to the modal gods with no luck. Any ideas?

Also, ./zsh_athame_setup.sh failed all four athame shell tests, but that's expected on OS X, correct?

**Comment by ardagnir** [comment]
It sounds like it's incorrectly sending returns for vim colon commands to the shell instead of vim. Can you check out refs/heads/0.7.2 and see if it fixes the problem?

**Comment by ardagnir** [comment]
Also, Zsh uses an incompatible version of test so I think the tests will fail for zsh on OS X regardless of whether it is actually broken (though whatever is wrong with Athame  in readline will probably break in zsh too)

**Comment by braham-snyder** [comment]
it's glorious--thanks!

**Comment by ardagnir** [comment]
Thanks! This should be fixed in master now.

**Comment by braham-snyder** [comment]
Happy to help!

Also, for what it's worth, the zsh setup script worked as well, but--unlike your bash script--it didn't automatically patch the shell in my bin (nor my homebrew version): it only patched the temporary zsh used for testing.

**Comment by ardagnir** [comment]
Did it give an error? Athame calls zsh's make install if the tests pass. It should install zsh to /usr/bin by default but it will say in the installation output where it is installing or why it failed.

**Comment by braham-snyder** [comment]
Ran it again just now and it definitely installed to /usr/bin/zsh successfully. I think the first time around I only entered "C" to continue once or twice before closing the window (mistakenly thinking that the same tests were being retried).

Thanks again!
