### ISSUE TITLE
Control-C doesn't work in athame

### ISSUE THREAD

**Issue by SirCmpwn** [ardagnir/athame#4]
Would be nice if some readline things still worked, such as ^D to exit, ^L to clear, ^C to abort the current line, etc.

**Comment by ardagnir** [comment]
<C-D> and <C-L> are now passed through to readline. <C-C> won't be until I fix athame's signal handling.

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by ardagnir** [comment]
^C is working in master
