### ISSUE TITLE
Zsh: Test 2 and 3, as well as Athame Shell Fallback test fail when using grml config

### ISSUE THREAD

**Issue by JohnDoe02** [ardagnir/athame#40]
Hey athame devs!
I was very happy when I found out about athame this weekend, yet it turned out that in its current state it is not working for me. I am on Arch Linux and am using zsh + grml config as my shell. The grml config is the standard one from the official repositories:
extra/grml-zsh-config 0.12.6-1 [installed]

When running the zsh_athame_setup.sh script, everything compiles fine. Some of the tests fail however:
`Testing Athame Shell...
Test 1:
Success!

Test 2:
Failed at high speed. Retrying at slower speed
Failed at slow speed.

Test 3:
Failed at high speed. Retrying at slower speed
Failed at slow speed.

Test 4:
Success!

Test Failed
Failed tests: 2 3

What now?
v: view failures
C: _DANGEROUS_ continue anyway
x: exit
C
Testing Athame Vim Integration...
Test 1:
Success!

Test 2:
Success!

Testing Athame Shell Fallback without X...
Test 1:
Success!

Test 2:`
The last test, Test 2 for Athame Shell Fallback without X, never completes and I have to kill the process.

After removing grml config from my system, all tests pass fine. readline+athame is also working fine.
Thanks for the great project. And let me know, if you need any more information.

**Comment by originalsouth** [comment]
Can confirm.

**Comment by ardagnir** [comment]
Should work now.
