### ISSUE TITLE
Distribution for Arch Linux

### ISSUE THREAD

**Issue by kovetskiy** [ardagnir/athame#49]
Hello. 

I want to create package for distribution Athame on Arch Linux using Arch User Repository (https://aur.archlinux.org/), Arch uses PKGBUILD (bash script) for building packages on client machine, and PKGBUILD provides special directive `sources` for files that must be downloaded and verified using signatures: https://wiki.archlinux.org/index.php/PKGBUILD#Sources

2 years ago I've tried to do it without bash script that provided in athame upstream (I guess it was not exists 2 years ago) here https://github.com/kovetskiy/athame-zsh-pkgbuild/blob/master/PKGBUILD
Now bash_readline_setup.sh contains lines with automatically downloading of bash and bash patches and now it's not compatible with Arch Linux build ecosystem, can you please add some flag line `--do-not-download` or may be create two separated scripts? 

Also it will be great to see separated commands for building and installing athame, like make and make install (now bash_readline_setup automatically runs make install for readline).

Thank you!

**Comment by ardagnir** [comment]
You shouldn't need bash_readline_setup.sh at all on Arch Linux. That's mostly a script to help Ubuntu/Debian people get a version of Bash that doesn't use a built-in readline.

The scripts are ugly though. I'll try to clean them up so that you can call individual sections.

**Comment by kovetskiy** [comment]
@ardagnir I can assign it on myself and send pull-request if you want.

**Comment by ardagnir** [comment]
Sounds great!

**Comment by SicariusNoctis** [comment]
Any updates on this?

**Comment by ardagnir** [comment]
Unassigning. I'll probably do this myself soon if nobody else wants to.

**Comment by shillshocked** [comment]
Please do...mono can be a pain to work with, it's nice when everything is all set up.

**Comment by ardagnir** [comment]
Athame is back in the AUR: https://aur.archlinux.org/packages/?K=athame
