### ISSUE TITLE
Isn't building from master on Mac OSX 10.10.2

### ISSUE THREAD

**Issue by base698** [ardagnir/athame#5]
```
./configure --prefix=/usr
make SHLIB_LIBS=-lncurses
```

### Error 
```
In file included from ../athame.c:30:
../history.h:35:12: fatal error: 'readline/rlstdc.h' file not found
```

**Comment by ardagnir** [comment]
Should be fixed now, but I can't test it.

**Comment by stephenmuss** [comment]
Compiled for me just now.

**Comment by base698** [comment]
How do you activate it?

**Comment by ardagnir** [comment]
Type bash to open a new shell and it should be running with athame. If not, OSX is probably looking for libraries in a weird place and you need to change the configure prefix.

Right now there's no way to activate/deactivate it. Vim mode is always on unless it fails (with angry red text).

**Comment by ardagnir** [comment]
Works on OSX now
