### ISSUE TITLE
Tab completion fails when menu-complete is set in .bashrc or .inputrc

### ISSUE THREAD

**Issue by tmilloff** [ardagnir/athame#58]
When menu-complete is enabled via `bind TAB:menu-complete` in .bashrc or `TAB:menu-complete` in .inputrc, the shell inserts a tab character rather than autocompleting when you press the tab key

**Comment by ardagnir** [comment]
I’ll look into including supporting bash menu options when I get a chance.

In the meantime, there’s a good chance that everything might just work if you swap rl_complete with rl_menu_complete in athame_readline.h.

**Comment by tmilloff** [comment]
Thanks for the suggestion. With that change, athame inserts a tab character, same as if I bound the option in my rc file. I might take a look at implementing the feature if I get a chance at some point as well.

**Comment by ardagnir** [comment]
Sorry, I meant change athame_readline in addition to the rc change.

The rl_complete in that file is saying to send the key bound to rl_complete to readline instead of vim.

**Comment by ardagnir** [comment]
Fixed in branch 1.1.2
