### ISSUE TITLE
Question - keep current state after executing command

### ISSUE THREAD

**Issue by yyoncho** [ardagnir/athame#59]
Is there a configuration option which will make `athame` to preserve the current state after executing a command? Currently if I am in normal state and I execute a command, it will change to insert state.

**Comment by ardagnir** [comment]
If you just want to start out in normal mode, comment out the athamerc line underneath the comment that says "Start each line in insert mode".

If you want to preserve the state of the previous line you should comment out that line and add "export ATHAME_VIM_PERSIST=1" to your bashrc/zshrc.

ATHAME_VIM_PERSIST will change other behavior as well (see the README for more info), but probably in ways you want if you don't like state being reset each line.

**Comment by yyoncho** [comment]
Thanks in worked out. Just for the record, I tried to set ATHAME_VIM_PERSIST but it does not work without the change in athamerc.
