### ISSUE TITLE
Athame Install error

### ISSUE THREAD

**Issue by Bavaria1664** [ardagnir/athame#64]
Hi,

I try to install your app with debian 9. I'm beginner in Unix environnement but i think have followed all the steps to install the program but when i wrote in command " ./readline_athame_setup.sh --libdir=/lib/x86_64-linux-gnu --use_sudo" i've this message:

No vim binary provided. Trying /usr/bin/vim
/usr/bin/vim probably has job support. Using /usr/bin/vim as vim binary.
./readline_athame_setup.sh: line 119: curl : command not found
./readline_athame_setup.sh: line 119: curl : command not found
./readline_athame_setup.sh: line 119: curl : command not found
Patching with standard readline patch 1
./readline_athame_setup.sh: ligne 142: ../readline_patches/readline70-$(printf "%03d" $patch): No file or folder of this type
Patching with standard readline patch 2
./readline_athame_setup.sh: line 142: ../readline_patches/readline70-$(printf "%03d" $patch): No file or folder of this type
Patching with standard readline patch 3
./readline_athame_setup.sh: line 142: ../readline_patches/readline70-$(printf "%03d" $patch): No file or folder of this type
Patching with Athame patch
patching file display.c
patching file Makefile.in
patching file readline.c
patching file shlib/Makefile.in
patching file readline.h
patching file callback.c
Copying Athame files
CONFIG_FILES=Makefile CONFIG_HEADERS= /bin/sh ./config.status
config.status: creating Makefile
awk: symbol lookup error: /usr/local/lib/libreadline.so.7: undefined symbol: UP
config.status: error: could not create Makefile
Makefile:188 : the recipe for the target « Makefile » failed
make: *** [Makefile] Error 127

Does anyone have a idea please?

**Comment by Bavaria1664** [comment]
i restarted the installation and now i've got this message:

No vim binary provided. Trying /usr/bin/vim
/usr/bin/vim probably has job support. Using /usr/bin/vim as vim binary.
./readline_athame_setup.sh: ligne 119: curl :  command not found
./readline_athame_setup.sh: ligne 119: curl :  command not found
./readline_athame_setup.sh: ligne 119: curl :  command not found
Patching with standard readline patch 1
./readline_athame_setup.sh: ligne 142: ../readline_patches/readline70-$(printf "%03d" $patch): No file or folder of this type
Patching with standard readline patch 2
./readline_athame_setup.sh: ligne 142: ../readline_patches/readline70-$(printf "%03d" $patch):  No file or folder of this type
Patching with standard readline patch 3
./readline_athame_setup.sh: ligne 142: ../readline_patches/readline70-$(printf "%03d" $patch): Aucun fichier ou dossier de ce type
Patching with Athame patch
patching file display.c
patching file Makefile.in
patching file readline.c
patching file shlib/Makefile.in
patching file readline.h
patching file callback.c
Copying Athame files
CONFIG_FILES=Makefile CONFIG_HEADERS= /bin/sh ./config.status
config.status: creating Makefile
awk: symbol lookup error: /usr/local/lib/libreadline.so.7: undefined symbol: UP
config.status: error: could not create Makefile
Makefile:188 : the recipe for the target « Makefile » failed
make: *** [Makefile] Erreur 127

Have anyone have idea?

**Comment by ardagnir** [comment]
You need curl. Probably sudo apt-get install curl. Not sure how the script even got as far as it did without it

**Comment by Bavaria1664** [comment]
Thanks for your reply. I 've installed curl .From cd athame , i try to launch readline_athame_setup.sh and i've this message at the begin "No vim binary provided. Trying /usr/bin/vim
/usr/bin/vim probably has job support. Using /usr/bin/vim as vim binary"

And at the end: "Testing Athame Shell...
Test 1:
speed=1116
Success!

Test 2:
speed=3393
Success!

Test 3:
speed=4479
Success!

Test 4:
speed=4090
Success!

Test 5:
speed=2920
Success!

Testing Athame Bash Shell...
Test 1:
speed=3600
Success!

Testing Athame Vim Integration...
Test 1:
speed=3360
Failed.

Test 2:
speed=3172
Failed.

Test 3:
speed=2592
Failed.

Test 4:
speed=2676
Failed.

Test 5:
speed=6622
Failed.

Test 6:
speed=1980
Failed.

Test Failed
Failed tests: 1 2 3 4 5 6"

Script finished on 13 jan. 2019 13:13:59
diff: out1: No file or folder of this type
The script started on 13 jan. 2019 13:13:59
bash-4.4# unset HISTFILE
bash-4.4# set nocompatible
bash-4.4# inoremap kj <ESC>
bash: syntax error near unexpected token `newline'
bash-4.4# iecho "test 2kj2h~b~A" > out2
bash: iecho: command not found
bash-4.4# exit
exit

Script terminé sur dim. 13 janv. 2019 13:13:59 CET
1d0
< TesT 2
Le script a débuté sur dim. 13 janv. 2019 13:13:59 CET
bash-4.4# unset HISTFILE
bash-4.4# echo 'vim'
vim
bash-4.4# echo 'is awesome' > out3
bash-4.4# f'vkf'c 
bash: fvkfc: command not found
bash-4.4# exit
exit

Script terminé sur dim. 13 janv. 2019 13:13:59 CET
1c1
< vim is awesome
---
> is awesome
Le script a débuté sur dim. 13 janv. 2019 13:13:59 CET
bash-4.4# unset HISTFILE
bash-4.4# echo "test 4lhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlA" >> out4
bash-4.4# exit
exit

Script terminé sur dim. 13 janv. 2019 13:13:59 CET
1c1
< test 4
---
> test 4lhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlA
Le script a débuté sur dim. 13 janv. 2019 13:13:59 CET
bash-4.4# unset HISTFILE
bash-4.4# export ATHAME_VIM_PERSIST=0
bash-4.4# echo xx > out5
bash-4.4# inoremap xx mapped
bash: inoremap: command not found
bash-4.4# iecho xx >> out5
bash: iecho: command not found
bash-4.4# echo xx >> out5
bash-4.4# export ATHAME_VIM_PERSIST=1
bash-4.4# echo xx >> out5
bash-4.4# inoremap xx mapped
bash: inoremap: command not found
bash-4.4# iecho xx >> out5
bash: iecho: command not found
bash-4.4# echo xx >> out5
bash-4.4# echo xx xx x >> out5
bash-4.4# export ATHAME_VIM_PERSIST=0
bash-4.4# echo z >> out5
bash-4.4# echo xx >> out5
bash-4.4# exit
exit

Script terminé sur dim. 13 janv. 2019 13:13:59 CET
2d1
< mapped
5,7c4,5
< mapped
< mapped
< mapped mapped x
---
> xx
> xx xx x
Le script a débuté sur dim. 13 janv. 2019 13:13:59 CET
bash-4.4# unset HISTFILE
bash-4.4# rm out6
rm: impossible de supprimer 'out6': Aucun fichier ou dossier de ce type
bash-4.4# echo ohno
ohno
bash-4.4# ex  mode             we made it > out6
bash-4.4# exit

Script terminé sur dim. 13 janv. 2019 13:14:00 CET
1d0
< we made it

What now?
v: view failures
C: *DANGEROUS* continue anyway
x: exit
v
Le script a débuté sur dim. 13 janv. 2019 13:13:59 CET
bash-4.4# unset HISTFILE
bash-4.4# echo "basic rtA" > out1xest
bash-4.4# echo "basic xest" >> out1bbbbrt
bash-4.4# exit
exit

Script finished on 13 jan. 2019 13:13:59
diff: out1: No file or folder of this type
The script started on  13 jan. 2019 13:13:59
bash-4.4# unset HISTFILE
bash-4.4# set nocompatible
bash-4.4# inoremap kj <ESC>
bash: syntax error near unexpected token `newline'
bash-4.4# iecho "test 2kj2h~b~A" > out2
bash: iecho: command not found
bash-4.4# exit
exit

Script finished on 13 jan. 2019 13:13:59
1d0
< TesT 2
The script started on 13 jan. 2019 13:13:59
bash-4.4# unset HISTFILE
bash-4.4# echo 'vim'
vim
bash-4.4# echo 'is awesome' > out3
bash-4.4# f'vkf'c 
bash: fvkfc: command not found
bash-4.4# exit
exit

Script finished on 13 jan. 2019 13:13:59 
1c1
< vim is awesome
---
> is awesome
The script started on 13 jan. 2019 13:13:59
bash-4.4# unset HISTFILE
bash-4.4# echo "test 4lhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlA" >> out4
bash-4.4# exit
exit

Script finished on. 13 jan. 2019 13:13:59
1c1
< test 4
---
> test 4lhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlA
The script started on  13 janv. 2019 13:13:59 
bash-4.4# unset HISTFILE
bash-4.4# export ATHAME_VIM_PERSIST=0
bash-4.4# echo xx > out5
bash-4.4# inoremap xx mapped
bash: inoremap: command not found
bash-4.4# iecho xx >> out5
bash: iecho: command not found
bash-4.4# echo xx >> out5
bash-4.4# export ATHAME_VIM_PERSIST=1
bash-4.4# echo xx >> out5
bash-4.4# inoremap xx mapped
bash: inoremap: command not found
bash-4.4# iecho xx >> out5
bash: iecho: command not found
bash-4.4# echo xx >> out5
bash-4.4# echo xx xx x >> out5
bash-4.4# export ATHAME_VIM_PERSIST=0
bash-4.4# echo z >> out5
bash-4.4# echo xx >> out5
bash-4.4# exit
exit

Script finished on 13 jan. 2019 13:13:59
2d1
< mapped
5,7c4,5
< mapped
< mapped
< mapped mapped x
---
> xx
> xx xx x
The script started on  13 jan. 2019 13:13:59
bash-4.4# unset HISTFILE
bash-4.4# rm out6
rm: impossible to delete 'out6':No file or folder of this type
bash-4.4# echo ohno
ohno
bash-4.4# ex  mode             we made it > out6
bash-4.4# exit

Script finished on 13 jan. 2019 13:14:00 
1d0
< we made it

 I confess I don't know what to do now.
