### ISSUE TITLE
Can't remove athame

### ISSUE THREAD

**Issue by RobertKirk** [ardagnir/athame#69]
I'd like to remove athame (sorry). I've already removed the zsh version, and now I'm trying to remove the readline version as psql uses readline and so is still using the athame readline.

I tried removing all the libreadline files in /usr/lib, as well downloading and building from source the gnu readline. but i always end up with athame in psql. Is there something I'm missing? even when I run the readline_athame_setup.sh with  --noathame it still uses athame. Any ideas how I can fix this? I've tried to remove everything related to athame, but whenever i use psql it still uses it, and now gets a athame vimbed error (presumable because that's not running anymore)

**Comment by ardagnir** [comment]
You should be able to use ldd to find which readline library file psql is using and delete that.

**Comment by RobertKirk** [comment]
Turned out psql actually links to a wrapper which dynamically links in the libreadline.so file, but I've deleted them now and then forceably reinstalled them,  sorry for bothering you.
