### ISSUE TITLE
Readline missing symbols

### ISSUE THREAD

**Issue by stratosmacker** [ardagnir/athame#7]
awk: symbol lookup error: /usr/lib/libreadline.so.6: undefined symbol: UP
 Is returned at a bash prompt on Arch Linux (more or less the latest version). Not sure why that is yet... but I am exploring it

**Comment by ardagnir** [comment]
By deafult, Arch Linux builds readline with curses support. It looks like you didn't. See the install section of the Athame readme.

**Comment by stratosmacker** [comment]
On April 9, 2015 1:01:13 AM EDT, ardagnir <notifications@github.com> wrote:
>By deafult, Arch Linux builds readline with curses support. It looks
>like you didn't. See the install section of the Athame readme.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ardagnir/athame/issues/7#issuecomment-91116022

Ahh but I did! Followed the instructions exactly. And ran ldconfig after like a good little programmer
-- 

Jesse

**Comment by ardagnir** [comment]
This is definitly a case of missing ncurses. Can you checkout the readline-6.3 tag (readline without athame) and building that with the same commands and see if it gives the same problem?

(Also, make sure you didn't make a typo in the make command.)
