### ISSUE TITLE
slow in command mode

### ISSUE THREAD

**Issue by cevhyruz** [ardagnir/athame#72]
vim version:            `8.1.948`
Operating system:  `Kali (linux 4.14.0)`
------------------------------------------------------

Athame installed as a local copy, no configuration.
vim has an empty `~/vimrc` and no other packages is loaded (checked with `:script` command).
yet it's a little laggy when typing in command mode any idea?

**Comment by ardagnir** [comment]
Command mode (:?/) is where athame is slowest because there are no autocmds. It shouldn’t be too slow but a ~100ms lag in command mode is normal

**Comment by cevhyruz** [comment]
I guess it should but mine was slower than in the demo on readme so I presume this is not a normal thing

**Comment by ardagnir** [comment]
For Vim 8.0.1445+ and Athame v1.2+, command mode  uses autocmds and should be as fast as the rest of Athame.
