### ISSUE TITLE
backspace doesnt do anything

### ISSUE THREAD

**Issue by grenzionky** [ardagnir/athame#74]
as the title says, instead the removing the character behind the cursor, pressing backspace moves the cursor left a character (as if i pressed it in normal mode)
this happens in every mode, including insert mode.

**Comment by ardagnir** [comment]
Does this happen in regular vim? Do you have nocompatible enabled?

**Comment by grenzionky** [comment]
it doesnt happen in regular vim. and it doesnt work regardless if nocompatible is on or off

**Comment by cevhyruz** [comment]
@grenzionky have you tried setting  `set backspace=indent,eol,start` in your vimrc?

**Comment by grenzionky** [comment]
i just checked again, and backspace is working correctly now, even without set backspace 🤷.
