### ISSUE TITLE
[Error] Athame Failure: XDG_RUNTIME_DIR environment variable not set

### ISSUE THREAD

**Issue by TheNordineLotfi** [ardagnir/athame#75]
Vim version: 8.1 (Huge version without gui)
(Has Job support enabled)
Distro: Debian 9
Installation Method: Safe option.

As the title of the issue mention, i noticed the following error when running the compiled bash in $HOME/local:
```Athame Failure: XDG_RUNTIME_DIR environment variable not set```
I also noticed similar error in the testing phase for Vim (Bash test were successful it seems, only the tests for Vim failed)
But since i wanted to test if it was actually working, i discarded the test, and tried it.

**Comment by TheNordineLotfi** [comment]
Output for ldd $(which bash):
	```linux-vdso.so.1 (0x00007ffdee052000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f1d5eefb000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1d5eef6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1d5ed35000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1d5f081000)```
(Executed on Athame bash found in $HOME/local)

**Comment by TheNordineLotfi** [comment]
Update: I think i managed to make it work with
```export XDG_RUNTIME_DIR=~/local```
in the Athame bash shell.
Not sure if it was the right way though.

**Comment by ardagnir** [comment]
~/local is fine. Athame just needs a private dir to store temp files/pipes and systemd creates $XDG_RUNTIME_DIR for this purpose. If you don't use systemd, you can just set it to whatever you want.
