### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by lxsli** [ardagnir/athame#8]
I followed the instructions in the README (everything seemed to work) but AFAICT Athame isn't working. I opened a new terminal window (IE new zsh) and still had emacs bindings. I then opened an interactive bash subshell, still no athame.

https://gist.github.com/lxsli/dba7c882c16a37651a9a

edit: running ldconfig hasn't helped

**Comment by lxsli** [comment]
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:59)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +cmdline_hist    +dnd             -footer          +lispindent      -mouse_jsbterm   +perl            +scrollbind      +tcl             +viminfo         -xterm_save
+arabic          +cmdline_info    -ebcdic          +fork()          +listcmds        +mouse_netterm   +persistent_undo +signs           +terminfo        +vreplace        +xpm
+autocmd         +comments        +emacs_tags      +gettext         +localmap        +mouse_sgr       +postscript      +smartindent     +termresponse    +wildignore
+balloon_eval    +conceal         +eval            -hangul_input    +lua             -mouse_sysmouse  +printer         -sniff           +textobjects     +wildmenu
+browse          +cryptv          +ex_extra        +iconv           +menu            +mouse_urxvt     +profile         +startuptime     +title           +windows
++builtin_terms  +cscope          +extra_search    +insert_expand   +mksession       +mouse_xterm     +python          +statusline      +toolbar         +writebackup
+byte_offset     +cursorbind      +farsi           +jumplist        +modify_fname    +multi_byte      -python3         -sun_workshop    +user_commands   +X11
+cindent         +cursorshape     +file_in_path    +keymap          +mouse           +multi_lang      +quickfix        +syntax          +vertsplit       -xfontset
+clientserver    +dialog_con_gui  +find_in_path    +langmap         +mouseshape      -mzscheme        +reltime         +tag_binary      +virtualedit     +xim
+clipboard       +diff            +float           +libcall         +mouse_dec       +netbeans_intg   +rightleft       +tag_old_static  +visual          +xsmp_interact
+cmdline_compl   +digraphs        +folding         +linebreak       +mouse_gpm       +path_extra      +ruby            -tag_any_white   +visualextra     +xterm_clipboard
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/
include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixma
n-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/in
clude/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk
-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lti
nfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7
/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -l
ruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib

**Comment by thedward** [comment]
Based on my (admittedly) limited understanding, this is intended to work with programs that are dynamically linked against libreadline ; Since, zsh uses zle instead I wouldn't expect that to work.

I assume it'll only work with bash when bash is dynamically (as opposed to statically) linked with libreadline (or if you recompile bash explicitly with this wrapper) ; The version of bash I have (Ubuntu 14.04) is not dynamically linked to libreadline so I can't confirm this.

**Comment by ardagnir** [comment]
If there's a problem with vim, athame will yell at you with angry red text, so if there's no difference athame didn't get installed or wasn't linked in by bash.

**Comment by lxsli** [comment]
OK so the solution is to recompile bash? I had a go but it looks like the default bash build (from https://ftp.gnu.org/gnu/bash/) includes source for readline. I think this has exceeded my hassle threshold now, I'll check back in six months.

https://gist.github.com/lxsli/3c138fbd2ff051a6ab70
