### ISSUE TITLE
How to debug Vimbed failure

### ISSUE THREAD

**Issue by Dovermore** [ardagnir/athame#80]
Hi, After updating to macOS Catalina my athame starts to fail with Vimbed failure, how can I diagnose the cause of this? Thanks.

**Comment by Dovermore** [comment]
I had this error 
```
Error detected while processing /SomePath/.vim/bundle/vimbed/plugin/vimbed.vim:
line  420:
E122: Function <SNR>94_VimLeave already exists, add ! to replace it
line  435:
E122: Function <SNR>94_WriteTabFile already exists, add ! to replace it
```
before I added `!` to the two functions. But after that, I still will get  `Athame Failure: Vimbed failure
`. How can I diagnose where Vimbed Failed?

**Comment by ardagnir** [comment]
Vimbed failure usually means vimbed isn't running at all or you're running a bad version. It might have been deleted from your lib directory when you updated your os.

If you want to try using vimbed from your bundle, make sure it matches the version included with your Athame source and add the following to your bashrc:
ATHAME_VIMBED_LOCATION=/SomePath/.vim/bundle/vimbed/plugin

**Comment by Dovermore** [comment]
Hi thanks for the response,

I have exported, 
`
export ATHAME_VIMBED_LOCATION=$HOME/.vim/bundle/vimbed/plugin
export ATHAME_ENABLED=1
`
in my `.zshrc`.
I am managing my `vimbed` with Vundle, shall I manually install vimbed instead?

**Comment by ardagnir** [comment]
Installing Athame normally installs vimbed to your libdir, but it doesn't really matter where it is as long as ATHAME_VIMBED_LOCATION is pointing to the right place.

**Comment by Dovermore** [comment]
I suppose the exact install way doesn't matter either. 
It seems even though I pointed out the `ATHAME_VIMBED_LOCATION` to my vimbed location. It still fails.
Nevertheless, thanks for the help and the great work making Athame. 
I think I will do a complete reinstall later when I got the time and then see if it works. I will close this for now.
