### ISSUE TITLE
Launch or test it's correctly installed 

### ISSUE THREAD

**Issue by soyuka** [ardagnir/athame#9]
Hi,

I'm running with `zsh` and `tmux` with `urxvt`. I just install athame and everything seems fine except some `mv`:

```
mv /usr/lib/libreadline.a /usr/lib/libreadline.old
mv: could not evaluate « /usr/lib/libreadline.a »: No such file or directory
make: [install-static] Erreur 1 (ignored)
/usr/bin/install -c -m 644 libreadline.a /usr/lib/libreadline.a
test -n "ranlib" && ranlib /usr/lib/libreadline.a
mv /usr/lib/libhistory.a /usr/lib/libhistory.old
mv: could not evaluate « /usr/lib/libhistory.a »: No such file or directory
make: [install-static] Erreur 1 (ignored)
/usr/bin/install -c -m 644 libhistory.a /usr/lib/libhistory.a
```

Now what? How can I check that the modded libreadline has been installed correctly? How may I test this? I've started a new `bash` shell (without `tmux`) but there is no `vi`. Theoretically this should work with `zsh` too?

Thanks! This project is looking great, hope it'll get through beta soon :)

**Comment by george-b** [comment]
Hi @soyuka zsh uses zle rather than readline so I wouldn't expect athame to work like it does in bash.

**Comment by soyuka** [comment]
Still, I've started bash in a new terminal but there is no changes :/.

**Comment by ardagnir** [comment]
If there's a problem with vim, athame will yell at you with angry red text, so if there's no difference athame didn't get installed or wasn't linked in by bash.

What OS are you using?

**Comment by zhoufeng1989** [comment]
Hi, thanks for the work, I install athame on My Mac OSX and I use Zsh,how can I activate it?

**Comment by soyuka** [comment]
@ardagnir I'm using Debian. How may I check that it get linked in by bash?

@zhoufeng1989 : 
> zsh uses zle rather than readline so I wouldn't expect athame to work like it does in bash

**Comment by ardagnir** [comment]
You would know if it did. Athame doesn't fail silently. It sounds like Debian uses static linking, so they compile bash to use it's own version of readline rather than a system one. You would have to recompile bash to get it to work.

This seems to be a common problem. I'll see if I can come up with an easier way to get athame working on Debain-based OSes.

**Comment by ardagnir** [comment]
Athame now works on zsh and I have included a script to force bash to use system readline.
